#下面这些内容是为了让MyBatis映射
#指定Mybatis的Mapper文件
spring:
  datasource:
    name: usercenter_fupan
    url: jdbc:mysql://localhost:3306/usercenter_fupan
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    # session失效时间
  session:
    timeout: 86400
    store-type: redis
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


      # redis 连接配置
  redis:
    port: 6379
    host: localhost
    database: 1
    connect-timeout: 100000
    # 不鼓励依赖循环引用，默认情况下是禁止的。更新您的应用程序以删除 bean 之间的依赖循环。作为最后的手段，可以通过将 spring.main.allow-circular-references 设置为 true 来自动中断循环。
  main:
    allow-circular-references: true

logging:
  level:
    com.sonkone.modules.system.mapper: debug
    org.springframework.boot.autoconfigure: ERROR


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    # 输出sql日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

server:
  servlet:
    context-path: /api
    session:
      cookie:
        domain:
  port: 8080

